#!/bin/bash

source ~/.bashrc

# Where's my Python
source /datascope/slurm/miniconda3/bin/activate viska-tf25
export PYTHONPATH=.:../pysynphot:../SciScript-Python/py3

# Where's my PFS 
export DNN_ROOT=/home/swei20/DNN
export DNN_DATA=/scratch/ceph/swei20/data/dnn
export DNN_TEST=/scratch/ceph/swei20/data/dnn/test


# Work around issues with saving weights when running on multiple threads
export HDF5_USE_FILE_LOCKING=FALSE

# Disable tensorflow deprecation warnings
export TF_CPP_MIN_LOG_LEVEL=2

# Enable more cores for numexpr
export NUMEXPR_MAX_THREADS=32


cd $DNN_ROOT

echo "Infer! Infer! "
echo "Data directory is $DNN_DATA"